// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.30;

/// @title IEZKLHalo2Verifier
/// @notice Interface for an EZKL Halo2 verifier
interface IEZKLHalo2Verifier {
    /* FUNCTIONS */

    /// @notice Verify a proof and public signals pair
    /// @dev This may revert on invalid proof and public signals pairs
    /// @param proof The proof generated by EZKL
    /// @param publicSignals The public signals generated by EZKL
    /// @return success Whether the proof and public signals pair is valid
    function verifyProof(bytes memory proof, uint256[] memory publicSignals) external view returns (bool success);
}
